version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      #- cd cdk && npm install && cd -
  build:
    commands:
      - npm run build
      #- cd cdk && npx cdk deploy && cd -

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
  